# Generated by Django 4.2.27 on 2026-01-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_order_paid_at_order_quoted_price_gbp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='deposit_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quoted_price_gbp',
            new_name='final_amount_gbp',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stripe_session_id',
            new_name='stripe_deposit_session_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount_gbp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='final_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_final_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='deposit_gbp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
